name: telegram message
on: [push]
jobs:
  build:
    name: server
    runs-on: ubuntu-latest
    steps:
      - name: Display the path
        run: echo $PATH
        shell: bash
    
  send_telegram:
    #  if: github.repository == 'ciscojmg/ota-github'
    name: send_telegram
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: '1586067515'
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
